version: '3'
networks:
  reu.net:
    driver: bridge
services:
#####################################################
# API SERVICES
#####################################################

  # service api.events : api frontoffice pour la gestion des evenements
  api.events:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.events.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '62360:80'
      - '62361:443'
    volumes:
      - './reu_events_service/public:/var/www/public'
      - './reu_events_service/src:/var/www/src'
    working_dir: /var/www/src
    networks:
      reu.net:
        aliases:
          - api.events.local
    depends_on:
      - mysql.events

  # service api.suivi.authentification : api backoffice pour l'autentification
  api.authentication:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.authentification.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '62362:80'
      - '62363:443'
    volumes:
      - './reu_authentification_service/public:/var/www/public'
      - './reu_authentification_service/src:/var/www/src'
    working_dir: /var/www/src
    networks:
      reu.net:
        aliases:
          - api.authentification.local
    depends_on:
      - mysql.users
  
  api.backoffice:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.backoffice.local
      - VHOST_DOCROOT=/var/www/pub
    ports:
      - '62364:80'
      - '62365:443'
    volumes:
      - './reu_backoffice_service/pub:/var/www/pub'
      - './reu_backoffice_service/src:/var/www/src'
      - './reu_backoffice_service/log:/var/log/app'
    working_dir: /var/www/src
    networks:
      reu.net:
        aliases:
          - api.backoffice.local

  # service sql pour le stockage des events -
  # utilisé par l'api  events et l'api comments
  mysql.events:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=comroot
      - MYSQL_USER=events_reu
      - MYSQL_PASSWORD=events_reu
      - MYSQL_DATABASE=events_reu
    ports:
      - '62366:3306'
    networks:
      - reu.net
    volumes:
      - './reu_events_service/sql:/var/sql'


  # service sql pour le stockage des users -
  # utilisé par l'api users 
  mysql.users:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=comroot
      - MYSQL_USER=users_reu
      - MYSQL_PASSWORD=users_reu
      - MYSQL_DATABASE=users_reu
    ports:
      - '62367:3309'                            
    networks:
      - reu.net
    volumes:
      - './reu_authentification_service/sql:/var/sql'

#
# service administration des bases sql
#
  adminer:
    image: adminer
    ports:
      - '62368:8080'
    networks:
      - reu.net

